# Generated by Django 5.2 on 2025-04-29 02:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid5, editable=False, primary_key=True, serialize=False)),
                ('on_date', models.DateField()),
                ('goods', models.TextField()),
                ('mores', models.TextField()),
                ('nexts', models.TextField()),
            ],
        ),
    ]
