# Generated by Django 5.2 on 2025-05-18 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_report_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='achievement_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='achievement_score',
            field=models.CharField(blank=True, choices=[('VERY_GOOD', '◎'), ('GOOD', '◯'), ('SOSO', '△'), ('NG', '✗')]),
        ),
        migrations.AddField(
            model_name='report',
            name='daily_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='daily_title',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='weekly_target',
            field=models.TextField(blank=True),
        ),
    ]
